name: TheNoobyGodsSMP-Core
main: gamercoder215.smpcore.Main
version: 3.0.2
api-version: 1.17
author: GamerCoder215
softdepend: [CrazyAdvancementsAPI, ProtocolLib]
description: Powers NoobyGodsSMP with bosses, abilities, and more.
commands:
  # User
  help:
    description: Gives you help with the new features.
    aliases: [?, hlp]
  bed:
    description: Teleports you to your spawnpoint.
    aliases: [bedspawn, bd]
  menu:
    description: Opens up the SMP GUI Menu.
    aliases: [smpmenu, smenu, playermenu, m]
  boss:
    description: Opens up the SMP Bosses Menu.
  craft:
    description: Open up a crafting menu.
    aliases: [craftingmenu, table, ctable]
  enderchest:
    description: Open up your ender chest.
    aliases: [ec, enderc, echest]
  creaturesguide:
    description: Opens up the creature guide.
    aliases: [cg, creatuesg, cguide, csg, creatureguide, csguide]
  trades:
    description: Opens up a menu where you can trade items for different items.
    aliases: [tmenu, trademenu, trade, t, tradem, tm]
  abilities:
    description: Opens up a menu where you can choose different abilities based on your skills.
    aliases: [ability, ab, abil, abils]
  worldchat:
    description: Allows you to chat with the players directly in your world.
    aliases: [wc, worldc, wchat]
  wandinfo:
    description: Get information about a wand.
    aliases: [winfo, wi, wandi, spellinfo, spelli, sinfo, si]
  emojilist:
    description: List emojis.
    aliases: [emojil, el, listemojis, elist, liste, le]
  # Admin
  invsee:
    description: Look at a player's inventory.
    aliases: [inventorysee, isee, inventorys]
    permission: core.admin.invsee
    permission-message: You do not have permission to use this command.
  flyspeed:
    description: Control your fly speed.
    aliases: [fspeed, flys, fs]
    permission: core.admin.flyspeed
    permission-message: You do not have permission to use this command.
  ecsee:
    description: Look at a player's ender chest.
    permission: core.admin.invsee
    permission-message: You do not have permission to use this command.
  allowflight:
    description: Allows or disallows a player's flight.
  getcustomitem:  
    description: Get a custom item.
    aliases: [gci, getci, gcustomi, gcitem]
    permission: core.admin.getcustomitem
    permission-message: You do not have permission to use this command.
  spawncustomentity:
    description: Summon a custom entity.
    aliases: [sce, spawnce, scustome, scentity, spawncustome, scustomentity, spawncentity]
  rejoinplayers:
    description: Makes players rejoin.
    aliases: [rjp, rejoinp, rjoinp, rjplayers, rjpl]
    permission: core.admin.rejoinplayers
    permission-message: You do not have permission to use this command.
  editplayer:
    description: Edits a player's attributes.
    aliases: [editp, ep]
    permission: core.admin.editplayer
    permission-message: You do not have permission to use this command.
  codertest:
    description: Main command for testing
    aliases: [ctest, ct, codert]
  ban:
    description: Ban a player.
    aliases: [b, yeetintothesun, yeetintolesun, hammer]
    permission: core.admin.ban
    permission-message: You do not have permission to use this command.
  suspend:
    description: Suspend a player (temp ban)
    aliases: [tempban, tban, yeetintospace, yeetintolespace, softban]
  titanwarps:
    description: Opens up the Titan Warps menu.
    aliases: [twarps, tw, titanw]
  setrank:
    description: Sets a players rank.
    aliases: [srank, setr, sr]
  getstatistic:
    description: Gets a player's statistic.
    aliases: [gets, gstatistic, gs, getplayerstatistic, getplayers, gplayerstatistic, gpstatistic, gps]
    permission: core.admin.getstatistic
    permission-message: You do not have permission to use this command.   
  
  
permissions:
  core.*:
    description: Gives all access to NoobyGodsSMP-Core Commands
    children:
      core.admin: true
      core.special: true
  core.special:
    description: Special permission, unlockable through certain items.
    default: op
  core.special.itemprotector:
    description: Prevents your items from getting despawned.
    children:
      core.special: true
  # Admininstrator
  core.admin:
    description: Gives all access to NoobyGodsSMP-Core Administrator Commands
    default: op
  core.admin.gamemodebypass:
    description: Bypass the movement gamemode resetter
    default: op
    children:
      core.admin: true
  core.admin.invsee:
    description: Allows you to see other inventories.
    children:
      core.admin: true
  core.admin.spawnboss:
    description: Allows you to spawn custom bosses;
    children:
      core.admin: true
  core.admin.suspend:
    description: Allows you to suspend someone.
    children:
      core.admin: true
  core.admin.ban:
    description: Allows you to ban someone.
    children:
      core.admin: true
  core.admin.getcustomitem:
    description: Allows you to get a custom item.
    children:
      core.admin: true
  core.admin.flyspeed:
    description: Allows you to customize flyspeed.
    children:
      core.admin: true
  core.admin.rejoinplayers:
    description: Allows you to initiate a rejoin.
    children:
      core.admin: true
  core.admin.invsee:
    description: Allows you to see inventories.
    children:
      core.admin: true
  core.admin.getstatistic:
    description: Allows you to fetch statistics.
    children:
      core.admin: true
  core.admin.editplayer:
    description: Allows you to edit a player.
    children:
      core.admin: true
  core.admin.ecsee:
    description: Allows you to see a player's enderchest.
    children:
      core.admin: true
 